<a href="https://colab.research.google.com/github/Brylimo/go-game-ranking-prediction-machine/blob/master/prediction_machine2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load data and labels

In [ ]:
import numpy as np
from google.colab import drive

#load train data and label
drive.mount('/content/drive')
train_data_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/train_data.npy" # Your train data file
train_label_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/train_label.npy" # Your train label file

train_data = np.load(train_data_path, allow_pickle=True)
train_label_rawdata = np.load(train_label_path, allow_pickle=True)  
num_train_data = len(train_data)

# character rating to integer rating
rating = ['18k', '17k', '16k', '15k', '14k', '13k', '12k', '11k', '10k', 
          '9k', '8k', '7k', '6k', '5k', '4k', '3k', '2k', '1k',
          '1d', '2d', '3d', '4d', '5d', '6d', '7d', '8d', '9d']

train_label = np.zeros(num_train_data)
for i in range(num_train_data):
  train_label_temp = train_label_rawdata[i]
  train_label_idx = rating.index(train_label_temp)
  train_label[i] = train_label_idx

# load test data and label
test_data_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/test_data.npy"
test_data = np.load(test_data_path, allow_pickle=True)
num_test_data = len(test_data)

test_label_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/test_label2.npy"
test_label_rawdata = np.load(test_label_path, allow_pickle=True)

test_label = np.zeros(num_test_data)
for i in range(num_test_data):
  test_label_temp = test_label_rawdata[i]
  test_label_idx = rating.index(test_label_temp)
  test_label[i] = test_label_idx


Mounted at /content/drive


## Last train data

In [ ]:
print(train_data.shape) # train_data is a list

(2682,)


In [ ]:
#check data shape
print(len(train_data[0]))
print(train_data[0][0].shape)

265
(1, 19, 19)


In [ ]:
print(len(train_data[1]))
print(train_data[1][0].shape)

245
(1, 19, 19)


In [ ]:
print(len(train_data[2]))
print(train_data[2][0].shape)

246
(1, 19, 19)


In [ ]:
# Get last baduk data of first game (바둑경기 전체 수순에서 마지막 바둑판의 장면)
teamp_last_data = train_data[0][-1]
print(teamp_last_data) # 1 denotes a black stone. -1 denotes a white stone. 0 denotes an empty position.

[[[ 0  0  0 -1  0  1  0  0  0  0  0  0 -1 -1 -1  1  1  0  1]
  [ 0 -1 -1  0 -1  1 -1  1 -1 -1  0 -1  0 -1  0 -1  1  1  0]
  [-1  0 -1 -1  1  0  1  1 -1  1 -1 -1 -1  0  0 -1  1 -1  1]
  [ 0 -1  1  1  1  1  0  0 -1  1  1  1 -1 -1 -1  1  1 -1 -1]
  [ 0  1  1  0  0  0  0  1 -1 -1  1  1  1  1  1  1 -1 -1  0]
  [ 0  0  0  0  0  0  0  1  1 -1 -1  1  1 -1  1  1 -1 -1 -1]
  [ 0  0  0  0  0  1  1 -1 -1  1 -1 -1 -1 -1  1  1  1 -1  0]
  [ 0  0  0  0  0  1 -1  0 -1  0  1  1  0 -1 -1  1 -1  0 -1]
  [ 0  0  1 -1 -1  1 -1  1 -1  1  0  1 -1  0  1 -1 -1  0  0]
  [ 0  1  1  1  1 -1  0 -1  0 -1  1 -1  0 -1 -1 -1  0 -1 -1]
  [ 0  0  1 -1 -1 -1 -1 -1 -1  0  1  0 -1  0  0  1 -1 -1  0]
  [ 0  1  1  0  0  0 -1  0 -1  1  0  1  1  0  0  0  1 -1  0]
  [ 0 -1  1 -1 -1 -1  1 -1  0  0  1  0  0  1  1  0  1 -1  0]
  [ 0  0 -1  1  1  1  1  1  1  1  0  0 -1 -1  1  0  1  1 -1]
  [-1 -1  0 -1  1  0  0  0 -1  1  0  0 -1  0 -1  1  1 -1  0]
  [-1  1 -1 -1 -1 -1  0 -1  0 -1  1  0 -1  0 -1 -1 -1 -1 -1]
  [ 1  0  1  1  1 -1  0 

In [ ]:
# Get last baduk data of all game
last_train_data = np.zeros( (num_train_data, 19,19) )

for i in range(num_train_data):
  temp_last_data = train_data[i][-1]
  last_train_data[i, :, :] = temp_last_data

In [ ]:
# Print last_train_data shape and contents
print(last_train_data.shape) # shape
print(last_train_data[50]) # content of 50-th games

(2682, 19, 19)
[[-1.  0. -1. -1.  0. -1.  0. -1.  0. -1.  0. -1. -1. -1. -1.  1.  0.  1.
   0.]
 [-1.  0. -1.  0. -1. -1.  0. -1. -1. -1.  0. -1.  0. -1. -1.  1.  1.  1.
   1.]
 [ 0. -1.  0. -1. -1. -1. -1.  0. -1. -1. -1.  0.  0. -1. -1.  1.  0.  1.
   1.]
 [-1.  0. -1. -1.  0.  0. -1. -1.  0. -1. -1.  0. -1. -1. -1.  1.  1.  1.
   1.]
 [-1. -1.  0. -1. -1. -1.  0. -1. -1. -1.  0. -1.  0. -1. -1. -1. -1.  1.
  -1.]
 [ 0.  0. -1.  0. -1.  0. -1. -1. -1. -1. -1.  0.  0. -1. -1.  0. -1. -1.
  -1.]
 [-1. -1. -1. -1. -1. -1. -1.  0. -1.  0. -1. -1. -1. -1.  0. -1.  1.  1.
  -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  1.  1. -1.  0. -1.  1.  0.  1.
   1.]
 [-1.  0. -1.  0. -1. -1. -1. -1. -1.  1.  0.  1. -1. -1.  1.  0.  1.  0.
   1.]
 [ 0. -1. -1. -1. -1.  1.  1.  1. -1.  1.  1.  1.  1.  1.  0.  1.  0.  1.
   1.]
 [-1. -1.  0. -1.  1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.
   0.]
 [ 0. -1.  0. -1.  1.  0.  1.  1.  0.  1.  1.  1.  0.  1.  0.  1.  0.  1.
   1.]
 [-1. -1. -1.

In [ ]:
# Prepare data for training SVM
last_train_data = np.reshape(last_train_data,(num_train_data, 19*19))
print(last_train_data.shape) # check shape of last_train_data

(2682, 361)


## Submit(final)

In [ ]:
# 전체 합치기(train_data 100%)
new_train_data = np.concatenate((train_data, test_data), axis=0)
new_train_label = np.concatenate((train_label, test_label), axis=0)

num_new_train_data = len(new_train_data)
print(new_train_label.shape)

(5372,)


In [ ]:
test2_data_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/Test2_data.npy"
test2_data = np.load(test2_data_path, allow_pickle=True)

In [ ]:
print(test2_data.shape)

(2700,)


In [ ]:
num_test2_data = len(test2_data)

In [ ]:
# train_data 100%
import sys
import pandas as pd
import numpy as np
from lightgbm import LGBMClassifier

arr = np.zeros((num_test2_data, 27))

total = 20
for j in range(total):
  real_train_label = new_train_label.copy()
  real_train_label = pd.DataFrame(real_train_label)
  real_train_data = pd.DataFrame(np.zeros((num_new_train_data, 19*19)))
  k = 0
  for i in range(num_new_train_data):
    if k >= real_train_data.shape[0]:
      break
    length = len(new_train_data[k])
    if length > j: 
      temp = pd.Series(new_train_data[k][j].reshape(19*19))
      real_train_data.iloc[k, :] = temp
    else:
      real_train_data.drop([k], axis=0, inplace=True)
      real_train_label.drop([k], axis=0, inplace=True)
    k+=1
  
  k = 0
  real_test2_data = pd.DataFrame(np.zeros((num_test2_data, 19*19)))
  chek = []
  for i in range(num_test2_data):
    if k >= real_test2_data.shape[0]:
      break 
    length = len(test2_data[k])
    if length > j:
      temp = pd.Series(test2_data[k][j].reshape(19*19))
      real_test2_data.iloc[k, :] = temp
    else:
      chek.append(i)
    k+=1

  clf = LGBMClassifier(n_estimator=500, learning_rate=0.05)
  clf.fit(real_train_data, real_train_label.values.ravel())
  pred_proba = clf.predict_proba(real_test2_data)

  count = np.full((num_test2_data, 1), total)
  for i in chek:
    pred_proba[i] = np.zeros((27, ))
    count[i] = count[i] - 1
  arr = arr + pred_proba

arr = arr / count
s_result = np.argmax(arr, axis=1)

In [ ]:
s_result

In [ ]:
submit = list_data = [str(rating[int(a)]).strip('\n\r') for a in s_result]
submit

In [ ]:
!pip install pycryptodomex --no-binary :all:

In [ ]:
!python -m Cryptodome.SelfTest

In [ ]:
import json
from base64 import b64encode
from Cryptodome.Cipher import AES
from Cryptodome.Util.Padding import pad

def read_txt(fileName):
    with open(fileName, 'rt') as f:
        list_data = [a.strip('\n\r') for a in f.readlines()]
    return list_data

def write_json(fileName, data):
    with open(fileName, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

def load_key(key_path):
    with open(key_path, "rb") as f:
        key = f.read()
    return key

def encrypt_data(key_path, ans_list, encrypt_store_path='ans.json'):
    key = load_key(key_path)
    data = " ".join([str(i) for i in ans_list])
    encode_data = data.encode()
    cipher = AES.new(key, AES.MODE_CBC)
    ct_bytes = cipher.encrypt(pad(encode_data, AES.block_size))
    iv = b64encode(cipher.iv).decode('utf-8')
    ct = b64encode(ct_bytes).decode('utf-8')
    write_json(encrypt_store_path, {'iv':iv, 'ciphertext':ct})

if __name__=="__main__":
    # 1.이메일을 통해서 전달 받은 키 파일의 경로 입력
    key_path = "/content/drive/My Drive/team5.pem"
    # 2. 예측한 결과를 텍스트 파일로 저장했을 경우 리스트로 다시 불러오기
    # 본인이 원하는 방식으로 리스트 형태로 예측 값을 불러오기만 하면 됨(순서를 지킬것)
    # raw_ans_path = "ans.txt"
    # ans = read_txt(raw_ans_path)
    ans = submit
    # 3. 암호화된 파일을 저장할 위치
    encrypt_ans_path = "/content/drive/My Drive/ans.json"
    # 4. 암호화!(pycrytodome 설치)
    encrypt_data(key_path, ans, encrypt_ans_path)

In [ ]:
df = pd.DataFrame(arr, columns=rating)
df.to_csv("/content/drive/My Drive/final.csv")

## Support Vector Machine

In [ ]:
# 아래 new method(test_data 25%, train_data 75%)를 실행하게 된다면 먼저 실행해야함
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(last_train_data, train_label)

NameError: ignored

In [ ]:
# Get test data
test_data_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/test_data.npy"
test_data = np.load(test_data_path, allow_pickle=True)

NameError: ignored

In [ ]:
# Get last test data
num_test_data = len(test_data)

last_test_data = np.zeros( (num_test_data, 19, 19) )

for i in range(num_test_data):
  temp_last_data = test_data[i][-1]
  last_test_data[i, :, :] = temp_last_data

last_test_data = np.reshape(last_test_data, (num_test_data, 19*19))

In [ ]:
# Predict test labels
pred_test_label = clf.predict(last_test_data)

In [ ]:
# Get test labels (student does not have this ground-truth of test data)
test_label_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/test_label2.npy"
test_label_rawdata = np.load(test_label_path, allow_pickle=True)
test_label = np.zeros(num_test_data)
for i in range(num_test_data):
  test_label_temp = test_label_rawdata[i]
  test_label_idx = rating.index(test_label_temp)
  test_label[i] = test_label_idx

In [ ]:
# Accuracy on test data with SVM (baseline accuracy is 1/26=0.384)
print('Accuracy on test data: ' + str(sum(pred_test_label==test_label)/len(test_label)))

## new method

In [ ]:
'''
# test_data split
from sklearn.model_selection import StratifiedKFold
import pandas as pd

skf = StratifiedKFold(n_splits=2)
n_iter=0
train_idx = None
test_idx = None

for train_index, test_index in skf.split(last_test_data, test_label):
  if n_iter == 0:
    train_idx = train_index
    test_idx = test_index
  n_iter += 1

print(train_idx.shape)
'''

NameError: ignored

In [ ]:
'''
# new_train_data + new_test_data
new_train_data = np.concatenate((train_data, test_data[train_idx]), axis=0)
new_train_label = np.concatenate((train_label, test_label[train_idx]), axis=0)
new_test_data = test_data[test_idx]
new_test_label = test_label[test_idx]

num_new_train_data = len(new_train_data)
num_new_test_data = len(new_test_data)
'''

In [ ]:
#print(new_train_label.shape)

In [ ]:
'''
# test_data 25% + tain_data 75%일 때
import sys
import pandas as pd
import numpy as np
from xgboost import XGBClassifier

arr = np.zeros((num_new_test_data, 27))

# 첫번째 수순부터 20번째 수순까지 각 수순을 트레이닝하여 예측하고 예측 확률을 전부 합침
# 합한 예측 확률이 가장 높은 기력을 최종적으로 선택
total = 20
for j in range(total):
  real_train_label = new_train_label.copy()
  real_train_label = pd.DataFrame(real_train_label)
  real_train_data = pd.DataFrame(np.zeros((num_new_train_data, 19*19)))
  k = 0
  for i in range(num_new_train_data):
    if k >= real_train_data.shape[0]:
      break
    length = len(new_train_data[k])
    if length > j: 
      temp = pd.Series(new_train_data[k][j].reshape(19*19))
      real_train_data.iloc[k, :] = temp
    else:
      real_train_data.drop([k], axis=0, inplace=True)
      real_train_label.drop([k], axis=0, inplace=True)
    k+=1
  
  k = 0
  real_test_data = pd.DataFrame(np.zeros((num_new_test_data, 19*19)))
  chek = []
  for i in range(num_new_test_data):
    if k >= real_test_data.shape[0]:
      break 
    length = len(new_test_data[k])
    if length > j:
      temp = pd.Series(new_test_data[k][j].reshape(19*19))
      real_test_data.iloc[k, :] = temp
    else:
      chek.append(i)
    k+=1

  # https://www.analyticsvidhya.com/blog/2016/03/complete-guide-parameter-tuning-xgboost-with-codes-python/
  # ↑혹시 애매한 부분 있으면 참고하세요
  if j == 0:   
    clf = XGBClassifier(learning_rate =0.01, n_estimators=994, max_depth=2, min_child_weight=5, gamma=0, subsample=0.75, colsample_bytree=0.65, scale_pos_weight=1, random_state=156, reg_alpha=0)
  elif j == 1:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=236, max_depth=9, min_child_weight=1, gamma=0, subsample=0.85, colsample_bytree=0.8, scale_pos_weight=1, random_state=156, reg_alpha=0)
  elif j == 2:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=425, max_depth=5, min_child_weight=3, gamma=0.4, subsample=0.55, colsample_bytree=0.85, scale_pos_weight=1, random_state=156, reg_alpha=0.85)
  elif j == 3:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=284, max_depth=6, min_child_weight=1, gamma=0.0, subsample=0.6, colsample_bytree=0.7, scale_pos_weight=1, random_state=156, reg_alpha=0.005)
  elif j == 4:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=305, max_depth=7, min_child_weight=1, gamma=0.1, subsample=0.8, colsample_bytree=0.7, scale_pos_weight=1, random_state=156, reg_alpha=0)
  elif j == 5:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=473, max_depth=4, min_child_weight=3, gamma=0, subsample=0.8, colsample_bytree=0.8, scale_pos_weight=1, random_state=156, reg_alpha=0)
  elif j == 6:  
    clf = XGBClassifier(learning_rate =0.01, n_estimators=585, max_depth=3, min_child_weight=1, gamma=0.3, subsample=0.8, colsample_bytree=0.75, scale_pos_weight=1, random_state=156, reg_alpha=0.01)
  elif j == 7:  
    clf = XGBClassifier(learning_rate =0.01, n_estimators=344, max_depth=5, min_child_weight=5, gamma=0, subsample=0.8, colsample_bytree=0.8, scale_pos_weight=1, random_state=156, reg_alpha=1e-5)
  elif j == 8:  
    clf = XGBClassifier(learning_rate =0.01, n_estimators=654, max_depth=3, min_child_weight=1, gamma=0.2, subsample=0.6, colsample_bytree=0.7, scale_pos_weight=1, random_state=156, reg_alpha=1e-5)
  elif j == 9: 
    clf = XGBClassifier(learning_rate =0.01, n_estimators=279, max_depth=9, min_child_weight=1, gamma=0.2, subsample=0.8, colsample_bytree=0.8, scale_pos_weight=1, random_state=156, reg_alpha=5e-05)
  elif j == 15:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=280, max_depth=10, min_child_weight=2, gamma=0.4, subsample=0.8, colsample_bytree=0.8, scale_pos_weight=1, random_state=156, reg_alpha=0.01)
  elif j == 16:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=297, max_depth=7, min_child_weight=3, gamma=0, subsample=0.85, colsample_bytree=0.85, scale_pos_weight=1, random_state=156, reg_alpha=0)
  elif j == 17:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=303, max_depth=5, min_child_weight=5, gamma=0, subsample=0.8, colsample_bytree=0.75, scale_pos_weight=1, random_state=156, reg_alpha=1)
  elif j == 18:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=217, max_depth=7, min_child_weight=3, gamma=0.2, subsample=0.7, colsample_bytree=0.65, scale_pos_weight=1, random_state=156, reg_alpha=0)
  elif j == 19:
    clf = XGBClassifier(learning_rate =0.01, n_estimators=178, max_depth=9, min_child_weight=5, gamma=0, subsample=0.8, colsample_bytree=0.8, scale_pos_weight=1, random_state=156, reg_alpha=0.01)
  else:
    clf = XGBClassifier(n_estimators=500, learning_rate=0.05, random_state=156)

  clf.fit(real_train_data, real_train_label.values.ravel())
  pred_proba = clf.predict_proba(real_test_data)

  count = np.full((num_new_test_data, 1), total)
  for i in chek:
    pred_proba[i] = np.zeros((27, ))
    count[i] = count[i] - 1
  arr = arr + pred_proba

arr = arr / count
result = np.argmax(arr, axis=1)
'''

In [ ]:
'''
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(new_test_label, result)
print('정확도: {}'.format(accuracy))
'''

# 바둑판 대칭

## 가로

In [ ]:
import copy
sup_train_data = copy.deepcopy(new_train_data)
for i in range(num_new_train_data):
  length = len(sup_train_data[i])
  for j in range(length):
      temp_sup_data = np.fliplr(sup_train_data[i][j][0])
      sup_train_data[i][j][0][:,:] = temp_sup_data

In [ ]:
sup_train_data.shape

In [ ]:
new_train_data.shape

In [ ]:
# 변형 합친 데이터
sup_train_label = copy.deepcopy(new_train_label)
new_train_data1 = np.concatenate((new_train_data, sup_train_data), axis=0)
new_train_label1 = np.concatenate((new_train_label, sup_train_label), axis=0)

In [ ]:
num_new_train_data1 = len(new_train_data1)

In [ ]:
new_train_data1.shape

In [ ]:
new_train_label1.shape

##세로

In [ ]:
import copy
train_data_rv = copy.deepcopy(new_train_data)
for i in range(num_new_train_data):
  length = len(sup_train_data[i])
  for j in range(length):
      temp_sup_data = np.flipud(train_data_rv[i][j][0])
      train_data_rv[i][j][0][:,:] = temp_sup_data

#train_data_rv  : new_train_data를 세로 대칭한 데이터셋

NameError: ignored

##대각선

In [ ]:

#대각선 대칭

#우상향 대각선
new_train_data_di_r = new_train_data

for i in range(num_new_train_data) :
  for j in range(len(new_train_data[i])):
    #print(i, j)
    for x in range(19) :
      for y in range(19) :
        new_train_data_di_r[i][j][0][x][y]=new_train_data[i][j][0][18-y][18-x]


#좌상향 대각선
new_train_data_di_l = new_train_data

for i in range(num_new_train_data) :
  for j in range(len(new_train_data[i])):
    #print(i, j)
    for x in range(19) :
      for y in range(19) :
        new_train_data_di_l[i][j][0][x][y]=new_train_data[i][j][0][y][x]


new_train_data3=np.concatenate((new_train_data,new_train_data_di_r), axis=0)
new_train_label3=np.concatenate((new_train_label, new_train_label), axis=0)

new_train_data3=np.concatenate((new_train_data3,new_train_data_di_l), axis=0)
new_train_label3=np.concatenate((new_train_label3, new_train_label), axis=0)


In [ ]:
new_train_data3.shape

(16116,)

In [ ]:
new_train_data3.shape

(16116,)

##회전

In [ ]:
# 시계방향으로 90도 회전
def rotate_CW_train_data(train_data):
  length = len(train_data)
  rotated = train_data.copy()

  for i in range(length):
    temp_game = train_data[i]
    for j in range(len(temp_game)):
      temp_play = temp_game[j][0]
      rotated_play = np.array(list(zip(*temp_play[::-1]))) 
      rotated[i][j][0] = rotated_play
  return rotated


In [ ]:
# train_data 100%, concat rotated data

temp_new_train_data = np.concatenate((train_data, test_data), axis=0)
temp_new_train_label = np.concatenate((train_label, test_label), axis=0)

#회전한 데이터 붙이기 
rotated_train_data = rotate_CW_train_data(temp_new_train_data) 
temp_new_train_data = np.concatenate((temp_new_train_data, rotated_train_data), axis=0) #1번 회전

rotated_train_data = rotate_CW_train_data(rotated_train_data)
temp_new_train_data = np.concatenate((temp_new_train_data, rotated_train_data), axis=0) #2번 회전

rotated_train_data = rotate_CW_train_data(rotated_train_data)
new_train_data4 = np.concatenate((temp_new_train_data, rotated_train_data), axis=0) #3번 회전

temp_new_train_label = np.concatenate((temp_new_train_label, temp_new_train_label), axis=0)  #2배
new_train_label4 = np.concatenate((temp_new_train_label, temp_new_train_label), axis=0)  #4배


num_new_train_data4 = len(new_train_data4)

print(new_train_data4.shape)
print(new_train_label4.shape)

In [ ]:



import sys
import pandas as pd
import numpy as np
from lightgbm import LGBMClassifier

arr = np.zeros((num_test2_data, 27))

total = 22

for j in range(total):
  real_train_label = new_train_label.copy()
  real_train_label = pd.DataFrame(real_train_label)
  real_train_data = pd.DataFrame(np.zeros((num_new_train_data, 19*19)))
  k = 0
  for i in range(num_new_train_data):
    if k >= real_train_data.shape[0]:
      break
    length = len(new_train_data[k])
    if length > j: 
      temp = pd.Series(new_train_data[k][j].reshape(19*19))
      real_train_data.iloc[k, :] = temp
    else:
      real_train_data.drop([k], axis=0, inplace=True)
      real_train_label.drop([k], axis=0, inplace=True)
    k+=1
  
  k = 0
  real_test2_data = pd.DataFrame(np.zeros((num_test2_data, 19*19)))
  chek = []
  for i in range(num_test2_data):
    if k >= real_test2_data.shape[0]:
      break 
    length = len(test2_data[k])
    if length > j:
      temp = pd.Series(test2_data[k][j].reshape(19*19))
      real_test2_data.iloc[k, :] = temp
    else:
      chek.append(i)
    k+=1

  clf = LGBMClassifier(n_estimator=500)
  clf.fit(real_train_data, real_train_label.values.ravel())
  pred_proba = clf.predict_proba(real_test2_data)

  count = np.full((num_test2_data, 1), total)
  for i in chek:
    pred_proba[i] = np.zeros((27, ))
    count[i] = count[i] - 1
  arr = arr + pred_proba

arr = arr / count
s_result = np.argmax(arr, axis=1)