<a href="https://colab.research.google.com/github/Brylimo/go-game-ranking-prediction-machine/blob/master/prediction_machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from google.colab import drive

#load train data and label
drive.mount('/content/drive')
train_data_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/train_data.npy" # Your train data file
train_label_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/train_label.npy" # Your train label file

train_data = np.load(train_data_path, allow_pickle=True)
train_label_rawdata = np.load(train_label_path, allow_pickle=True)  

num_train_data = len(train_data)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
print(train_data.shape) # train_data is a list

(2682,)


In [4]:
#check data shape
print(len(train_data[0]))
print(train_data[0][0].shape)

265
(1, 19, 19)


In [5]:
print(len(train_data[1]))
print(train_data[1][0].shape)

245
(1, 19, 19)


In [6]:
print(len(train_data[2]))
print(train_data[2][0].shape)

246
(1, 19, 19)


In [7]:
# Get last baduk data of first game (바둑경기 전체 수순에서 마지막 바둑판의 장면)
teamp_last_data = train_data[0][-1]
print(teamp_last_data) # 1 denotes a black stone. -1 denotes a white stone. 0 denotes an empty position.

[[[ 0  0  0 -1  0  1  0  0  0  0  0  0 -1 -1 -1  1  1  0  1]
  [ 0 -1 -1  0 -1  1 -1  1 -1 -1  0 -1  0 -1  0 -1  1  1  0]
  [-1  0 -1 -1  1  0  1  1 -1  1 -1 -1 -1  0  0 -1  1 -1  1]
  [ 0 -1  1  1  1  1  0  0 -1  1  1  1 -1 -1 -1  1  1 -1 -1]
  [ 0  1  1  0  0  0  0  1 -1 -1  1  1  1  1  1  1 -1 -1  0]
  [ 0  0  0  0  0  0  0  1  1 -1 -1  1  1 -1  1  1 -1 -1 -1]
  [ 0  0  0  0  0  1  1 -1 -1  1 -1 -1 -1 -1  1  1  1 -1  0]
  [ 0  0  0  0  0  1 -1  0 -1  0  1  1  0 -1 -1  1 -1  0 -1]
  [ 0  0  1 -1 -1  1 -1  1 -1  1  0  1 -1  0  1 -1 -1  0  0]
  [ 0  1  1  1  1 -1  0 -1  0 -1  1 -1  0 -1 -1 -1  0 -1 -1]
  [ 0  0  1 -1 -1 -1 -1 -1 -1  0  1  0 -1  0  0  1 -1 -1  0]
  [ 0  1  1  0  0  0 -1  0 -1  1  0  1  1  0  0  0  1 -1  0]
  [ 0 -1  1 -1 -1 -1  1 -1  0  0  1  0  0  1  1  0  1 -1  0]
  [ 0  0 -1  1  1  1  1  1  1  1  0  0 -1 -1  1  0  1  1 -1]
  [-1 -1  0 -1  1  0  0  0 -1  1  0  0 -1  0 -1  1  1 -1  0]
  [-1  1 -1 -1 -1 -1  0 -1  0 -1  1  0 -1  0 -1 -1 -1 -1 -1]
  [ 1  0  1  1  1 -1  0 

In [8]:
# Get last baduk data of all game
last_train_data = np.zeros( (num_train_data, 19,19) )

for i in range(num_train_data):
  temp_last_data = train_data[i][-1]
  last_train_data[i, :, :] = temp_last_data

In [9]:
# Print last_train_data shape and contents
print(last_train_data.shape) # shape
print(last_train_data[50]) # content of 50-th games

(2682, 19, 19)
[[-1.  0. -1. -1.  0. -1.  0. -1.  0. -1.  0. -1. -1. -1. -1.  1.  0.  1.
   0.]
 [-1.  0. -1.  0. -1. -1.  0. -1. -1. -1.  0. -1.  0. -1. -1.  1.  1.  1.
   1.]
 [ 0. -1.  0. -1. -1. -1. -1.  0. -1. -1. -1.  0.  0. -1. -1.  1.  0.  1.
   1.]
 [-1.  0. -1. -1.  0.  0. -1. -1.  0. -1. -1.  0. -1. -1. -1.  1.  1.  1.
   1.]
 [-1. -1.  0. -1. -1. -1.  0. -1. -1. -1.  0. -1.  0. -1. -1. -1. -1.  1.
  -1.]
 [ 0.  0. -1.  0. -1.  0. -1. -1. -1. -1. -1.  0.  0. -1. -1.  0. -1. -1.
  -1.]
 [-1. -1. -1. -1. -1. -1. -1.  0. -1.  0. -1. -1. -1. -1.  0. -1.  1.  1.
  -1.]
 [ 0. -1.  0. -1.  0. -1.  0. -1.  0. -1.  1.  1. -1.  0. -1.  1.  0.  1.
   1.]
 [-1.  0. -1.  0. -1. -1. -1. -1. -1.  1.  0.  1. -1. -1.  1.  0.  1.  0.
   1.]
 [ 0. -1. -1. -1. -1.  1.  1.  1. -1.  1.  1.  1.  1.  1.  0.  1.  0.  1.
   1.]
 [-1. -1.  0. -1.  1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.
   0.]
 [ 0. -1.  0. -1.  1.  0.  1.  1.  0.  1.  1.  1.  0.  1.  0.  1.  0.  1.
   1.]
 [-1. -1. -1.

In [10]:
# Prepare data for training SVM
last_train_data = np.reshape(last_train_data,(num_train_data, 19*19))
print(last_train_data.shape) # check shape of last_train_data

(2682, 361)


In [11]:
# Prepare label for training SVM
rating = ['18k', '17k', '16k', '15k', '14k', '13k', '12k', '11k', '10k', 
          '9k', '8k', '7k', '6k', '5k', '4k', '3k', '2k', '1k',
          '1d', '2d', '3d', '4d', '5d', '6d', '7d', '8d', '9d']

In [12]:
# Prepare label for training SVM (character rating to integer rating)
train_label = np.zeros(num_train_data)
for i in range(num_train_data):
  train_label_temp = train_label_rawdata[i]
  train_label_idx = rating.index(train_label_temp)
  train_label[i] = train_label_idx

In [13]:
print(sum(train_label==0)) # number of '18k' 
print(sum(train_label==26)) # number of '9d'

99
100


## Support Vector Machine

In [14]:
# Train SVM using training data and label (This part shoud be done by ML algorithm!) --> Key part! (학생 여러분들은 여기에 머신러닝 알고리즘을 구현하면 됩니다. 가장 중요한 부분입니다.)
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(last_train_data, train_label)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [15]:
# Get test data
test_data_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/test_data.npy"
test_data = np.load(test_data_path, allow_pickle=True)

In [16]:
# Get last test data
num_test_data = len(test_data)

last_test_data = np.zeros( (num_test_data, 19, 19) )

for i in range(num_test_data):
  temp_last_data = test_data[i][-1]
  last_test_data[i, :, :] = temp_last_data

last_test_data = np.reshape(last_test_data, (num_test_data, 19*19))

In [17]:
# Predict test labels
pred_test_label = clf.predict(last_test_data)

In [18]:
# Get test labels (student does not have this ground-truth of test data)
test_label_path = "/content/drive/Shareddrives/기계학습5조/colab_data/baduk/test_label2.npy"
test_label_rawdata = np.load(test_label_path, allow_pickle=True)
test_label = np.zeros(num_test_data)
for i in range(num_test_data):
  test_label_temp = test_label_rawdata[i]
  test_label_idx = rating.index(test_label_temp)
  test_label[i] = test_label_idx

In [19]:
# Accuracy on test data with SVM (baseline accuracy is 1/26=0.384)
print('Accuracy on test data: ' + str(sum(pred_test_label==test_label)/len(test_label)))

Accuracy on test data: 0.04498141263940521


## XGBoost

In [20]:
import xgboost

print(xgboost.__version__)

0.90


In [27]:
from xgboost import XGBClassifier

xgb_clf = XGBClassifier(n_estimators=500, learning_rate=0.05, random_state=156)
xgb_clf.fit(last_train_data, train_label)

'\nfrom xgboost import XGBClassifier\n\nxgb_clf = XGBClassifier(n_estimators=500, learning_rate=0.05, random_state=156)\nxgb_clf.fit(last_train_data, train_label)\n'

In [29]:
pred_test_label_xgb = xgb_clf.predict(last_test_data)

In [28]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(test_label, pred_test_label_xgb)
print('정확도: {0}'.format(accuracy))

"\nfrom sklearn.metrics import accuracy_score\n\naccuracy = accuracy_score(test_label, pred_test_label_xgb)\nprint('정확도: {0}'.format(accuracy))\n"

In [ ]:
from xgboost import plot_importance
import matplotlib.pyplot as plt
%matplotlib inline

fig, ax = plt.subplots(figsize=(20, 54))
plot_importance(xgb_clf, ax=ax)

### hyperparameter tuning

In [ ]:
# params = {'max_depth': [5, 7], 'min_child_weight': [1, 3], 'colsample_bytree':[0.5, 0.75]}

In [ ]:
'''
from sklearn.model_selection import GridSearchCV

gridcv = GridSearchCV(xgb_clf, param_grid=params, cv=3, refit=True)
gridcv.fit(last_train_data, train_label)
print('GridSearchCV 최적 파라미터:', gridcv.best_params_)
print('GridSearchCV 최고 정확도:{0}'.format(gridcv.best_score_))
'''

# 최적 파라미터: {'colsample_bytree':0.75, 'max_depth': 5, 'min_child_weight':1}

In [24]:
xgb_clf = XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=156, max_depth=5, min_child_weight=1, colsample_bytree=0.75)
xgb_clf.fit(last_train_data, train_label)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.75, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=156,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [25]:
from sklearn.metrics import accuracy_score
pred_test_label_xgb = xgb_clf.predict(last_test_data)

accuracy = accuracy_score(test_label, pred_test_label_xgb)
print('정확도: {}'.format(accuracy))

정확도: 0.07323420074349442


## LightGBM

In [ ]:
from lightgbm import LGBMClassifier

lgbm_clf = LGBMClassifier(n_estimator=100)

lgbm_clf.fit(last_train_data, train_label)

In [ ]:
pred_test_label_lgbm = lgbm_clf.predict(last_test_data)

In [ ]:
accuracy_lgbm = accuracy_score(test_label, pred_test_label_lgbm)
print('정확도: {}'.format(accuracy_lgbm))

## Stacking

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

# 개별 ML 모델
knn_clf = KNeighborsClassifier(n_neighbors=4)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=123)
dt_clf = DecisionTreeClassifier()
ada_clf = AdaBoostClassifier(n_estimators=100)

# 메타 ML 모델
lr_clf = LogisticRegression(C=10)


In [ ]:
knn_clf.fit(last_train_data, train_label)
rf_clf.fit(last_train_data, train_label)
dt_clf.fit(last_train_data, train_label)
ada_clf.fit(last_train_data, train_label)

In [ ]:
knn_pred = knn_clf.predict(last_test_data)
rf_pred = rf_clf.predict(last_test_data)
dt_pred = dt_clf.predict(last_test_data)
ada_pred = ada_clf.predict(last_test_data)

# 개별 모델 예측 정확도
print('KNN 정확도: {}'.format(accuracy_score(test_label, knn_pred)))
print('랜덤 포레스트 정확도: {}'.format(accuracy_score(test_label, rf_pred)))
print('Decision Tree 정확도: {}'.format(accuracy_score(test_label, dt_pred)))
print('Ada Boost 정확도: {}'.format(accuracy_score(test_label, ada_pred)))

In [ ]:
from sklearn.model_selection import KFold

def create_dataset(model, X_train, y_train, X_test, n_folds):
  kf = KFold(n_splits=n_folds, shuffle=False, random_state=0)

  train_fold_pred = np.zeros((X_train.shape[0], 1))
  test_pred = np.zeros((X_test.shape[0], n_folds))
  print(model.__class__.__name__, ' model start ')

  for cnt, (train_index, valid_index) in enumerate(kf.split(X_train)):
    X_tr = X_train[train_index]
    y_tr = y_train[train_index]
    X_te = X_train[valid_index]

    model.fit(X_tr, y_tr)
    train_fold_pred[valid_index, :] = model.predict(X_te).reshape(-1, 1)
    test_pred[:, cnt] = model.predict(X_test)

  test_pred_mean = np.mean(test_pred, axis=1).reshape(-1, 1)
  return train_fold_pred, test_pred_mean

In [ ]:
knn_train, knn_test = create_dataset(knn_clf, last_train_data, train_label, last_test_data, 7)
rf_train, rf_test = create_dataset(rf_clf, last_train_data, train_label, last_test_data, 7)
dt_train, dt_test = create_dataset(dt_clf, last_train_data, train_label, last_test_data, 7)
ada_train, ada_test = create_dataset(ada_clf, last_train_data, train_label, last_test_data, 7)

In [ ]:
final_X_train = np.concatenate((knn_train, rf_train, dt_train, ada_train), axis=1)
final_X_test = np.concatenate((knn_test, rf_test, dt_test, ada_test), axis=1)

lr_clf.fit(final_X_train, train_label)
final = lr_clf.predict(final_X_test)

print('최종 메타 모델의 예측 정확도: {}'.format(accuracy_score(test_label, final)))

## Foolish Support Vector Machine

In [ ]:
# Train foolish SVM 
import random
from sklearn.svm import LinearSVC

train_label_foo = train_label
random.shuffle(train_label_foo) # shuffle ground-truth labels!

clf_foo = LinearSVC()
clf_foo.fit(last_train_data, train_label_foo)
pred_test_label_foo = clf_foo.predict(last_test_data)

In [ ]:
# Accuracy on test data with foolish SVM (baseline accuracy is 1/26=0.384)
print('Accuracy on test data: ' + str(sum(pred_test_label_foo==test_label)/len(test_label)))